#!/usr/bin/env python3

API_KEY = 'aaa'
API_SECRET = 'bbb'
EMAIL_FROM = 'ccc@mail.com'
EMAIL_TO = 'ddd@mail.com'
EMAIL_PASS = 'eee'
HISTORIC_PATH = 'fff'
LOGS_PATH = 'ggg'
BUY_PATH = 'hhh'
SELL_PATH = 'iii'
FLAG_PATH = 'jjj'
DIFF_PATH = 'kkk'
TELEGRAM_TOKEN = 'lll'
TELEGRAM_CHAT_ID = 'mmm'
